// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package repo

import (
	"context"
)

const getCategoryIDBySlug = `-- name: GetCategoryIDBySlug :one
SELECT id
FROM categories
WHERE slug = $1
`

func (q *Queries) GetCategoryIDBySlug(ctx context.Context, slug string) (int64, error) {
	row := q.db.QueryRow(ctx, getCategoryIDBySlug, slug)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, slug
FROM categories
ORDER BY name
`

type ListCategoriesRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) ListCategories(ctx context.Context) ([]ListCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoriesRow
	for rows.Next() {
		var i ListCategoriesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
