// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: incidents.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countIncidents = `-- name: CountIncidents :one
SELECT count(*)
FROM incidents i
JOIN categories c ON c.id = i.category_id
WHERE ($1::text = '' OR c.slug = $1::text)
    AND ($2::text = '' OR i.status::text = $2::text)
    AND ($3::text = '' OR EXISTS (
        SELECT 1
        FROM incident_tags it2
        JOIN tags t2 ON t2.id = it2.tag_id
        WHERE it2.incident_id = i.id AND t2.slug = $3::text
    ))
    AND ($4::text = ''
        OR i.search_vector @@ websearch_to_tsquery('coelbook', $4::text)
        -- Substring fallbacks: partial words while typing ("postg"), and
        -- snippet content, which is code and isn't in search_vector.
        OR i.title ILIKE '%' || $4::text || '%'
        OR i.summary ILIKE '%' || $4::text || '%'
        OR EXISTS (
            SELECT 1
            FROM snippets s
            WHERE s.incident_id = i.id AND s.content ILIKE '%' || $4::text || '%'
        ))
`

type CountIncidentsParams struct {
	Category string `json:"category"`
	Status   string `json:"status"`
	Tag      string `json:"tag"`
	Query    string `json:"query"`
}

func (q *Queries) CountIncidents(ctx context.Context, arg CountIncidentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countIncidents,
		arg.Category,
		arg.Status,
		arg.Tag,
		arg.Query,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIncident = `-- name: CreateIncident :one
INSERT INTO incidents (
    title, slug, summary, problem, diagnosis, root_cause, solution, prevention,
    status, category_id, created_by
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11
)
RETURNING id
`

type CreateIncidentParams struct {
	Title      string         `json:"title"`
	Slug       string         `json:"slug"`
	Summary    pgtype.Text    `json:"summary"`
	Problem    pgtype.Text    `json:"problem"`
	Diagnosis  pgtype.Text    `json:"diagnosis"`
	RootCause  pgtype.Text    `json:"root_cause"`
	Solution   pgtype.Text    `json:"solution"`
	Prevention pgtype.Text    `json:"prevention"`
	Status     IncidentStatus `json:"status"`
	CategoryID int64          `json:"category_id"`
	CreatedBy  int64          `json:"created_by"`
}

func (q *Queries) CreateIncident(ctx context.Context, arg CreateIncidentParams) (int64, error) {
	row := q.db.QueryRow(ctx, createIncident,
		arg.Title,
		arg.Slug,
		arg.Summary,
		arg.Problem,
		arg.Diagnosis,
		arg.RootCause,
		arg.Solution,
		arg.Prevention,
		arg.Status,
		arg.CategoryID,
		arg.CreatedBy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getIncidentBySlug = `-- name: GetIncidentBySlug :one
SELECT
    i.id,
    i.title,
    i.slug,
    i.summary,
    i.problem,
    i.diagnosis,
    i.root_cause,
    i.solution,
    i.prevention,
    i.status,
    i.created_at,
    i.updated_at,
    c.name AS category_name,
    c.slug AS category_slug,
    u.first_name AS author_first_name,
    u.last_name AS author_last_name,
    COALESCE(
        (SELECT array_agg(t.name ORDER BY t.name)
         FROM incident_tags it
         JOIN tags t ON t.id = it.tag_id
         WHERE it.incident_id = i.id),
        '{}'::text[]
    ) AS tags
FROM incidents i
JOIN categories c ON c.id = i.category_id
JOIN users u ON u.id = i.created_by
WHERE i.slug = $1
`

type GetIncidentBySlugRow struct {
	ID              int64              `json:"id"`
	Title           string             `json:"title"`
	Slug            string             `json:"slug"`
	Summary         pgtype.Text        `json:"summary"`
	Problem         pgtype.Text        `json:"problem"`
	Diagnosis       pgtype.Text        `json:"diagnosis"`
	RootCause       pgtype.Text        `json:"root_cause"`
	Solution        pgtype.Text        `json:"solution"`
	Prevention      pgtype.Text        `json:"prevention"`
	Status          IncidentStatus     `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CategoryName    string             `json:"category_name"`
	CategorySlug    string             `json:"category_slug"`
	AuthorFirstName string             `json:"author_first_name"`
	AuthorLastName  string             `json:"author_last_name"`
	Tags            interface{}        `json:"tags"`
}

func (q *Queries) GetIncidentBySlug(ctx context.Context, slug string) (GetIncidentBySlugRow, error) {
	row := q.db.QueryRow(ctx, getIncidentBySlug, slug)
	var i GetIncidentBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Summary,
		&i.Problem,
		&i.Diagnosis,
		&i.RootCause,
		&i.Solution,
		&i.Prevention,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryName,
		&i.CategorySlug,
		&i.AuthorFirstName,
		&i.AuthorLastName,
		&i.Tags,
	)
	return i, err
}

const getIncidentVersion = `-- name: GetIncidentVersion :one
SELECT v.version, v.snapshot, v.changed_fields, v.created_at,
       u.first_name AS author_first_name, u.last_name AS author_last_name
FROM incident_versions v
JOIN incidents i ON i.id = v.incident_id
LEFT JOIN users u ON u.id = v.author_id
WHERE i.slug = $1 AND v.version = $2
`

type GetIncidentVersionParams struct {
	Slug    string `json:"slug"`
	Version int32  `json:"version"`
}

type GetIncidentVersionRow struct {
	Version         int32              `json:"version"`
	Snapshot        []byte             `json:"snapshot"`
	ChangedFields   []string           `json:"changed_fields"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	AuthorFirstName pgtype.Text        `json:"author_first_name"`
	AuthorLastName  pgtype.Text        `json:"author_last_name"`
}

func (q *Queries) GetIncidentVersion(ctx context.Context, arg GetIncidentVersionParams) (GetIncidentVersionRow, error) {
	row := q.db.QueryRow(ctx, getIncidentVersion, arg.Slug, arg.Version)
	var i GetIncidentVersionRow
	err := row.Scan(
		&i.Version,
		&i.Snapshot,
		&i.ChangedFields,
		&i.CreatedAt,
		&i.AuthorFirstName,
		&i.AuthorLastName,
	)
	return i, err
}

const incidentSlugExists = `-- name: IncidentSlugExists :one
SELECT EXISTS (SELECT 1 FROM incidents WHERE slug = $1)
`

func (q *Queries) IncidentSlugExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, incidentSlugExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listIncidentLinks = `-- name: ListIncidentLinks :many
SELECT id, title, url
FROM links
WHERE incident_id = $1
ORDER BY id
`

type ListIncidentLinksRow struct {
	ID    int64  `json:"id"`
	Title string `json:"title"`
	Url   string `json:"url"`
}

func (q *Queries) ListIncidentLinks(ctx context.Context, incidentID int64) ([]ListIncidentLinksRow, error) {
	rows, err := q.db.Query(ctx, listIncidentLinks, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIncidentLinksRow
	for rows.Next() {
		var i ListIncidentLinksRow
		if err := rows.Scan(&i.ID, &i.Title, &i.Url); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncidentSnippets = `-- name: ListIncidentSnippets :many
SELECT id, title, language, content
FROM snippets
WHERE incident_id = $1
ORDER BY "order", id
`

type ListIncidentSnippetsRow struct {
	ID       int64  `json:"id"`
	Title    string `json:"title"`
	Language string `json:"language"`
	Content  string `json:"content"`
}

func (q *Queries) ListIncidentSnippets(ctx context.Context, incidentID int64) ([]ListIncidentSnippetsRow, error) {
	rows, err := q.db.Query(ctx, listIncidentSnippets, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIncidentSnippetsRow
	for rows.Next() {
		var i ListIncidentSnippetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Language,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncidentVersions = `-- name: ListIncidentVersions :many
SELECT v.version, v.changed_fields, v.created_at,
       u.first_name AS author_first_name, u.last_name AS author_last_name
FROM incident_versions v
JOIN incidents i ON i.id = v.incident_id
LEFT JOIN users u ON u.id = v.author_id
WHERE i.slug = $1
ORDER BY v.version DESC
`

type ListIncidentVersionsRow struct {
	Version         int32              `json:"version"`
	ChangedFields   []string           `json:"changed_fields"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	AuthorFirstName pgtype.Text        `json:"author_first_name"`
	AuthorLastName  pgtype.Text        `json:"author_last_name"`
}

func (q *Queries) ListIncidentVersions(ctx context.Context, slug string) ([]ListIncidentVersionsRow, error) {
	rows, err := q.db.Query(ctx, listIncidentVersions, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIncidentVersionsRow
	for rows.Next() {
		var i ListIncidentVersionsRow
		if err := rows.Scan(
			&i.Version,
			&i.ChangedFields,
			&i.CreatedAt,
			&i.AuthorFirstName,
			&i.AuthorLastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncidents = `-- name: ListIncidents :many
SELECT
    i.id,
    i.title,
    i.slug,
    i.summary,
    i.status,
    i.created_at,
    i.updated_at,
    c.name AS category_name,
    c.slug AS category_slug,
    u.first_name AS author_first_name,
    u.last_name AS author_last_name,
    COALESCE(
        (SELECT array_agg(t.name ORDER BY t.name)
         FROM incident_tags it
         JOIN tags t ON t.id = it.tag_id
         WHERE it.incident_id = i.id),
        '{}'::text[]
    ) AS tags,
    (CASE WHEN $1::text = '' THEN ''
        ELSE ts_headline('coelbook', i.title, websearch_to_tsquery('coelbook', $1::text),
            'HighlightAll=true, StartSel=' || chr(57344) || ', StopSel=' || chr(57345))
    END)::text AS title_highlight,
    (CASE WHEN $1::text = '' THEN ''
        ELSE ts_headline('coelbook', coalesce(i.summary, ''), websearch_to_tsquery('coelbook', $1::text),
            'HighlightAll=true, StartSel=' || chr(57344) || ', StopSel=' || chr(57345))
    END)::text AS summary_highlight
FROM incidents i
JOIN categories c ON c.id = i.category_id
JOIN users u ON u.id = i.created_by
WHERE ($2::text = '' OR c.slug = $2::text)
    AND ($3::text = '' OR i.status::text = $3::text)
    AND ($4::text = '' OR EXISTS (
        SELECT 1
        FROM incident_tags it2
        JOIN tags t2 ON t2.id = it2.tag_id
        WHERE it2.incident_id = i.id AND t2.slug = $4::text
    ))
    AND ($1::text = ''
        OR i.search_vector @@ websearch_to_tsquery('coelbook', $1::text)
        -- Substring fallbacks: partial words while typing ("postg"), and
        -- snippet content, which is code and isn't in search_vector.
        OR i.title ILIKE '%' || $1::text || '%'
        OR i.summary ILIKE '%' || $1::text || '%'
        OR EXISTS (
            SELECT 1
            FROM snippets s
            WHERE s.incident_id = i.id AND s.content ILIKE '%' || $1::text || '%'
        ))
ORDER BY
    (CASE WHEN $1::text = '' THEN 0
        ELSE ts_rank(i.search_vector, websearch_to_tsquery('coelbook', $1::text))
    END) DESC,
    i.created_at DESC
LIMIT $6 OFFSET $5
`

type ListIncidentsParams struct {
	Query      string `json:"query"`
	Category   string `json:"category"`
	Status     string `json:"status"`
	Tag        string `json:"tag"`
	PageOffset int32  `json:"page_offset"`
	PageLimit  int32  `json:"page_limit"`
}

type ListIncidentsRow struct {
	ID               int64              `json:"id"`
	Title            string             `json:"title"`
	Slug             string             `json:"slug"`
	Summary          pgtype.Text        `json:"summary"`
	Status           IncidentStatus     `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CategoryName     string             `json:"category_name"`
	CategorySlug     string             `json:"category_slug"`
	AuthorFirstName  string             `json:"author_first_name"`
	AuthorLastName   string             `json:"author_last_name"`
	Tags             interface{}        `json:"tags"`
	TitleHighlight   string             `json:"title_highlight"`
	SummaryHighlight string             `json:"summary_highlight"`
}

// With a query, results are ordered by full-text relevance, and the title
// and summary come back with matched terms wrapped in U+E000 / U+E001
// (private-use characters, so they can't clash with real content and
// the client renders them as highlights without parsing HTML). Without a
// query, results are ordered by date and the highlight columns are empty.
func (q *Queries) ListIncidents(ctx context.Context, arg ListIncidentsParams) ([]ListIncidentsRow, error) {
	rows, err := q.db.Query(ctx, listIncidents,
		arg.Query,
		arg.Category,
		arg.Status,
		arg.Tag,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIncidentsRow
	for rows.Next() {
		var i ListIncidentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Summary,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.CategorySlug,
			&i.AuthorFirstName,
			&i.AuthorLastName,
			&i.Tags,
			&i.TitleHighlight,
			&i.SummaryHighlight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordIncidentVersion = `-- name: RecordIncidentVersion :execrows
WITH prev AS (
    SELECT v.version, v.snapshot
    FROM incident_versions v
    WHERE v.incident_id = $1
    ORDER BY v.version DESC
    LIMIT 1
), cur AS (
    SELECT incident_snapshot($1) AS snapshot
)
INSERT INTO incident_versions (incident_id, version, snapshot, changed_fields, author_id)
SELECT
    $1,
    coalesce((SELECT version FROM prev), 0) + 1,
    cur.snapshot,
    coalesce(
        (SELECT array_agg(k.key ORDER BY k.key)
         FROM jsonb_each(cur.snapshot) k, prev
         WHERE k.value IS DISTINCT FROM prev.snapshot -> k.key),
        '{}'::text[]),
    $2
FROM cur
WHERE NOT EXISTS (SELECT 1 FROM prev WHERE prev.snapshot = cur.snapshot)
`

type RecordIncidentVersionParams struct {
	IncidentID int64       `json:"incident_id"`
	AuthorID   pgtype.Int8 `json:"author_id"`
}

// Appends a version with the incident's current snapshot, listing the keys
// that differ from the previous version. A save that changed nothing adds
// no version (0 rows). Call it last in the write transaction, after tags,
// snippets and links; the incident row lock taken by that transaction keeps
// version numbers sequential.
func (q *Queries) RecordIncidentVersion(ctx context.Context, arg RecordIncidentVersionParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordIncidentVersion, arg.IncidentID, arg.AuthorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const refreshIncidentSearchVector = `-- name: RefreshIncidentSearchVector :exec
UPDATE incidents
SET search_vector = incident_search_vector(id)
WHERE id = $1
`

// Rebuilds the incident's full-text document; call it after any change to
// the incident, its tags or its snippets (see incident_search_vector()).
func (q *Queries) RefreshIncidentSearchVector(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, refreshIncidentSearchVector, id)
	return err
}

const refreshIncidentSearchVectors = `-- name: RefreshIncidentSearchVectors :exec
UPDATE incidents
SET search_vector = incident_search_vector(id)
WHERE id = ANY ($1::bigint[])
`

// Same as RefreshIncidentSearchVector for several incidents, e.g. every
// incident whose tag was just renamed, merged or deleted.
func (q *Queries) RefreshIncidentSearchVectors(ctx context.Context, ids []int64) error {
	_, err := q.db.Exec(ctx, refreshIncidentSearchVectors, ids)
	return err
}

const updateIncident = `-- name: UpdateIncident :one
UPDATE incidents
SET title       = $1,
    summary     = $2,
    problem     = $3,
    diagnosis   = $4,
    root_cause  = $5,
    solution    = $6,
    prevention  = $7,
    status      = $8,
    category_id = $9,
    updated_at  = now()
WHERE slug = $10
RETURNING id
`

type UpdateIncidentParams struct {
	Title      string         `json:"title"`
	Summary    pgtype.Text    `json:"summary"`
	Problem    pgtype.Text    `json:"problem"`
	Diagnosis  pgtype.Text    `json:"diagnosis"`
	RootCause  pgtype.Text    `json:"root_cause"`
	Solution   pgtype.Text    `json:"solution"`
	Prevention pgtype.Text    `json:"prevention"`
	Status     IncidentStatus `json:"status"`
	CategoryID int64          `json:"category_id"`
	Slug       string         `json:"slug"`
}

// The slug is deliberately left unchanged so existing links keep working
// when the title is edited.
func (q *Queries) UpdateIncident(ctx context.Context, arg UpdateIncidentParams) (int64, error) {
	row := q.db.QueryRow(ctx, updateIncident,
		arg.Title,
		arg.Summary,
		arg.Problem,
		arg.Diagnosis,
		arg.RootCause,
		arg.Solution,
		arg.Prevention,
		arg.Status,
		arg.CategoryID,
		arg.Slug,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
