// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links.sql

package repo

import (
	"context"
)

const createLink = `-- name: CreateLink :exec
INSERT INTO links (incident_id, title, url)
VALUES ($1, $2, $3)
`

type CreateLinkParams struct {
	IncidentID int64  `json:"incident_id"`
	Title      string `json:"title"`
	Url        string `json:"url"`
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) error {
	_, err := q.db.Exec(ctx, createLink, arg.IncidentID, arg.Title, arg.Url)
	return err
}

const deleteIncidentLinks = `-- name: DeleteIncidentLinks :exec
DELETE FROM links
WHERE incident_id = $1
`

func (q *Queries) DeleteIncidentLinks(ctx context.Context, incidentID int64) error {
	_, err := q.db.Exec(ctx, deleteIncidentLinks, incidentID)
	return err
}
