// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: snippets.sql

package repo

import (
	"context"
)

const createSnippet = `-- name: CreateSnippet :exec
INSERT INTO snippets (incident_id, title, language, content, "order")
VALUES ($1, $2, $3, $4, $5)
`

type CreateSnippetParams struct {
	IncidentID int64  `json:"incident_id"`
	Title      string `json:"title"`
	Language   string `json:"language"`
	Content    string `json:"content"`
	Position   int32  `json:"position"`
}

func (q *Queries) CreateSnippet(ctx context.Context, arg CreateSnippetParams) error {
	_, err := q.db.Exec(ctx, createSnippet,
		arg.IncidentID,
		arg.Title,
		arg.Language,
		arg.Content,
		arg.Position,
	)
	return err
}

const deleteIncidentSnippets = `-- name: DeleteIncidentSnippets :exec
DELETE FROM snippets
WHERE incident_id = $1
`

func (q *Queries) DeleteIncidentSnippets(ctx context.Context, incidentID int64) error {
	_, err := q.db.Exec(ctx, deleteIncidentSnippets, incidentID)
	return err
}
