// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countIncidentsByStatus = `-- name: CountIncidentsByStatus :many
SELECT status, count(*) AS total
FROM incidents
GROUP BY status
`

type CountIncidentsByStatusRow struct {
	Status IncidentStatus `json:"status"`
	Total  int64          `json:"total"`
}

func (q *Queries) CountIncidentsByStatus(ctx context.Context) ([]CountIncidentsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countIncidentsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountIncidentsByStatusRow
	for rows.Next() {
		var i CountIncidentsByStatusRow
		if err := rows.Scan(&i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentlyUpdatedIncidents = `-- name: RecentlyUpdatedIncidents :many
SELECT
    i.title,
    i.slug,
    i.status,
    i.updated_at,
    c.name AS category_name,
    c.slug AS category_slug
FROM incidents i
JOIN categories c ON c.id = i.category_id
ORDER BY i.updated_at DESC, i.id DESC
LIMIT $1
`

type RecentlyUpdatedIncidentsRow struct {
	Title        string             `json:"title"`
	Slug         string             `json:"slug"`
	Status       IncidentStatus     `json:"status"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	CategoryName string             `json:"category_name"`
	CategorySlug string             `json:"category_slug"`
}

func (q *Queries) RecentlyUpdatedIncidents(ctx context.Context, maxIncidents int32) ([]RecentlyUpdatedIncidentsRow, error) {
	rows, err := q.db.Query(ctx, recentlyUpdatedIncidents, maxIncidents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecentlyUpdatedIncidentsRow
	for rows.Next() {
		var i RecentlyUpdatedIncidentsRow
		if err := rows.Scan(
			&i.Title,
			&i.Slug,
			&i.Status,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.CategorySlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topTags = `-- name: TopTags :many
SELECT t.name, t.slug, count(*) AS incident_count
FROM incident_tags it
JOIN tags t ON t.id = it.tag_id
GROUP BY t.id, t.name, t.slug
ORDER BY incident_count DESC, t.name
LIMIT $1
`

type TopTagsRow struct {
	Name          string `json:"name"`
	Slug          string `json:"slug"`
	IncidentCount int64  `json:"incident_count"`
}

func (q *Queries) TopTags(ctx context.Context, maxTags int32) ([]TopTagsRow, error) {
	rows, err := q.db.Query(ctx, topTags, maxTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TopTagsRow
	for rows.Next() {
		var i TopTagsRow
		if err := rows.Scan(&i.Name, &i.Slug, &i.IncidentCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weeklyIncidentCreations = `-- name: WeeklyIncidentCreations :many
SELECT
    w.week_start::date AS week_start,
    count(i.id) AS total
FROM generate_series(
        date_trunc('week', now()) - ($1::int - 1) * interval '1 week',
        date_trunc('week', now()),
        interval '1 week'
    ) AS w(week_start)
LEFT JOIN incidents i
    ON i.created_at >= w.week_start AND i.created_at < w.week_start + interval '1 week'
GROUP BY w.week_start
ORDER BY w.week_start
`

type WeeklyIncidentCreationsRow struct {
	WeekStart pgtype.Date `json:"week_start"`
	Total     int64       `json:"total"`
}

// One row per week (Monday-based, in the database's time zone) for the
// last `weeks` weeks including the current one, oldest first; weeks with
// no incident are included with a zero count.
func (q *Queries) WeeklyIncidentCreations(ctx context.Context, weeks int32) ([]WeeklyIncidentCreationsRow, error) {
	rows, err := q.db.Query(ctx, weeklyIncidentCreations, weeks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WeeklyIncidentCreationsRow
	for rows.Next() {
		var i WeeklyIncidentCreationsRow
		if err := rows.Scan(&i.WeekStart, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
