// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package repo

import (
	"context"
)

const addIncidentTag = `-- name: AddIncidentTag :exec
INSERT INTO incident_tags (incident_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddIncidentTagParams struct {
	IncidentID int64 `json:"incident_id"`
	TagID      int64 `json:"tag_id"`
}

func (q *Queries) AddIncidentTag(ctx context.Context, arg AddIncidentTagParams) error {
	_, err := q.db.Exec(ctx, addIncidentTag, arg.IncidentID, arg.TagID)
	return err
}

const deleteIncidentTags = `-- name: DeleteIncidentTags :exec
DELETE FROM incident_tags
WHERE incident_id = $1
`

func (q *Queries) DeleteIncidentTags(ctx context.Context, incidentID int64) error {
	_, err := q.db.Exec(ctx, deleteIncidentTags, incidentID)
	return err
}

const upsertTag = `-- name: UpsertTag :one
INSERT INTO tags (name, slug)
VALUES ($1, $2)
ON CONFLICT (slug) DO UPDATE SET slug = EXCLUDED.slug
RETURNING id
`

type UpsertTagParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

// Returns the id of the tag with this slug, creating it if needed. The
// no-op update makes RETURNING yield the existing row on conflict.
func (q *Queries) UpsertTag(ctx context.Context, arg UpsertTagParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertTag, arg.Name, arg.Slug)
	var id int64
	err := row.Scan(&id)
	return id, err
}
