// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumePasswordResetToken = `-- name: ConsumePasswordResetToken :exec
UPDATE password_reset_tokens
SET used_at = now()
WHERE id = $1
  AND used_at IS NULL
`

func (q *Queries) ConsumePasswordResetToken(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, consumePasswordResetToken, id)
	return err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one
INSERT INTO password_reset_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, used_at, created_at
`

type CreatePasswordResetTokenParams struct {
	UserID    int64              `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, createPasswordResetToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, first_name, last_name)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, first_name, last_name, created_at, updated_at, session_version
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	FirstName    string `json:"first_name"`
	LastName     string `json:"last_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SessionVersion,
	)
	return i, err
}

const emailTakenByOtherUser = `-- name: EmailTakenByOtherUser :one
SELECT EXISTS (
    SELECT 1
    FROM users
    WHERE lower(email) = lower($1) AND id <> $2
)
`

type EmailTakenByOtherUserParams struct {
	Email  string `json:"email"`
	UserID int64  `json:"user_id"`
}

// Case-insensitive, like the address a user would type to sign in.
func (q *Queries) EmailTakenByOtherUser(ctx context.Context, arg EmailTakenByOtherUserParams) (bool, error) {
	row := q.db.QueryRow(ctx, emailTakenByOtherUser, arg.Email, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, email, password_hash, first_name, last_name, created_at, updated_at, session_version
FROM users
WHERE lower(email) = lower($1)
`

// Case-insensitive: an address is the same whatever case it is typed in
// (see the users_email_lower_key index).
func (q *Queries) FindUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SessionVersion,
	)
	return i, err
}

const findUserById = `-- name: FindUserById :one
SELECT id, email, password_hash, first_name, last_name, created_at, updated_at, session_version
FROM users
WHERE id = $1
`

func (q *Queries) FindUserById(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, findUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SessionVersion,
	)
	return i, err
}

const getValidPasswordResetTokenForUpdate = `-- name: GetValidPasswordResetTokenForUpdate :one
SELECT id, user_id
FROM password_reset_tokens
WHERE token_hash = $1
  AND used_at IS NULL
  AND expires_at > now()
FOR UPDATE
`

type GetValidPasswordResetTokenForUpdateRow struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetValidPasswordResetTokenForUpdate(ctx context.Context, tokenHash string) (GetValidPasswordResetTokenForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getValidPasswordResetTokenForUpdate, tokenHash)
	var i GetValidPasswordResetTokenForUpdateRow
	err := row.Scan(&i.ID, &i.UserID)
	return i, err
}

const hasUser = `-- name: HasUser :one
SELECT EXISTS (SELECT 1 FROM users) AS exists
`

func (q *Queries) HasUser(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, hasUser)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const invalidatePasswordResetTokens = `-- name: InvalidatePasswordResetTokens :exec
UPDATE password_reset_tokens
SET used_at = now()
WHERE user_id = $1
  AND used_at IS NULL
`

func (q *Queries) InvalidatePasswordResetTokens(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, invalidatePasswordResetTokens, userID)
	return err
}

const updateUserPasswordAndSessionVersion = `-- name: UpdateUserPasswordAndSessionVersion :exec
UPDATE users
SET password_hash   = $2,
    session_version = session_version + 1,
    updated_at      = now()
WHERE id = $1
`

type UpdateUserPasswordAndSessionVersionParams struct {
	ID           int64  `json:"id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdateUserPasswordAndSessionVersion(ctx context.Context, arg UpdateUserPasswordAndSessionVersionParams) error {
	_, err := q.db.Exec(ctx, updateUserPasswordAndSessionVersion, arg.ID, arg.PasswordHash)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET first_name = $1,
    last_name  = $2,
    email      = $3,
    updated_at = now()
WHERE id = $4
RETURNING id, email, password_hash, first_name, last_name, created_at, updated_at, session_version
`

type UpdateUserProfileParams struct {
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Email     string `json:"email"`
	ID        int64  `json:"id"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SessionVersion,
	)
	return i, err
}
