// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateSettings(ctx context.Context, arg CreateSettingsParams) (Setting, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	FindUserByEmail(ctx context.Context, email string) (User, error)
	FindUserById(ctx context.Context, id pgtype.UUID) (User, error)
	GetSettings(ctx context.Context) (Setting, error)
}

var _ Querier = (*Queries)(nil)
