// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package repo

import (
	"context"
)

const createSettings = `-- name: CreateSettings :one
INSERT INTO settings (instance_name, timezone, locale)
VALUES ($1, $2, $3)
RETURNING id, instance_name, timezone, locale, initialized_at
`

type CreateSettingsParams struct {
	InstanceName string `json:"instance_name"`
	Timezone     string `json:"timezone"`
	Locale       string `json:"locale"`
}

func (q *Queries) CreateSettings(ctx context.Context, arg CreateSettingsParams) (Setting, error) {
	row := q.db.QueryRow(ctx, createSettings, arg.InstanceName, arg.Timezone, arg.Locale)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.InstanceName,
		&i.Timezone,
		&i.Locale,
		&i.InitializedAt,
	)
	return i, err
}

const getSettings = `-- name: GetSettings :one
SELECT id, instance_name, timezone, locale, initialized_at
FROM settings
LIMIT 1
`

func (q *Queries) GetSettings(ctx context.Context) (Setting, error) {
	row := q.db.QueryRow(ctx, getSettings)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.InstanceName,
		&i.Timezone,
		&i.Locale,
		&i.InitializedAt,
	)
	return i, err
}
