// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

type Querier interface {
	ListUsers(ctx context.Context) (pgconn.CommandTag, error)
}

var _ Querier = (*Queries)(nil)
