// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

const listUsers = `-- name: ListUsers :execresult
SELECT id, email, password_hash, name, created_at, updated_at
FROM users
`

func (q *Queries) ListUsers(ctx context.Context) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, listUsers)
}
